name: CI/CD for React Native

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    android:
        name: Build Android
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up JDK 17
              uses: actions/setup-java@v2
              with:
                  java-version: "17"

            - name: Install Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "20"

            - name: Install dependencies
              run: yarn install

            - name: Build Android Release APK
              run: |
                  cd android
                  ./gradlew assembleRelease

            - name: Upload Android APK as an artifact
              uses: actions/upload-artifact@v2
              with:
                  name: android-app-release.apk
                  path: android/app/build/outputs/apk/release/app-release.apk

    ios:
        name: Build iOS
        runs-on: macos-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "20"

            - name: Install dependencies
              run: yarn install

            - name: Set up Ruby and CocoaPods
              uses: ruby/setup-ruby@v1
              with:
                  ruby-version: "2.7"

            - name: Install CocoaPods
              run: |
                  cd ios
                  pod install

            - name: Build iOS Release IPA
              run: |
                  cd ios
                  xcodebuild -workspace YourApp.xcworkspace -scheme YourApp -sdk iphoneos -configuration Release archive -archivePath $PWD/build/YourApp.xcarchive

            - name: Export IPA
              run: |
                  xcodebuild -exportArchive -archivePath $PWD/build/YourApp.xcarchive -exportOptionsPlist $PWD/exportOptions.plist -exportPath $PWD/build

            - name: Upload iOS IPA as an artifact
              uses: actions/upload-artifact@v2
              with:
                  name: ios-app-release.ipa
                  path: ios/build/YourApp.ipa
